stages:
  - build

build_image:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  only:
    refs:
      - master
      - tags
    changes:
      - Dockerfile
      - requirements.txt
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - TAG="${CI_COMMIT_TAG:-latest}"
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$TAG
  tags:
    - docker
